version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "00:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: com.google.firebase:firebase-bom
    versions:
    - 26.6.0
    - 26.7.0
    - 26.8.0
    - 27.0.0
  - dependency-name: androidx.recyclerview:recyclerview
    versions:
    - 1.2.0
  - dependency-name: org.mockito:mockito-inline
    versions:
    - 3.8.0
    - 3.9.0
  - dependency-name: org.mockito:mockito-core
    versions:
    - 3.8.0
    - 3.9.0
  - dependency-name: com.google.android.gms:oss-licenses-plugin
    versions:
    - 0.10.3
  - dependency-name: com.squareup.leakcanary:leakcanary-android-instrumentation
    versions:
    - "2.7"
  - dependency-name: com.squareup.leakcanary:plumber-android
    versions:
    - "2.7"
  - dependency-name: com.squareup.leakcanary:leakcanary-android-process
    versions:
    - "2.7"
  - dependency-name: com.google.firebase:firebase-crashlytics-gradle
    versions:
    - 2.5.1
    - 2.5.2
  - dependency-name: androidx.fragment:fragment-ktx
    versions:
    - 1.3.1
    - 1.3.2
  - dependency-name: androidx.activity:activity-ktx
    versions:
    - 1.2.1
    - 1.2.2
  - dependency-name: androidx.annotation:annotation
    versions:
    - 1.2.0
  - dependency-name: org.jetbrains.kotlin:kotlin-gradle-plugin
    versions:
    - 1.4.31
    - 1.4.32
  - dependency-name: com.android.tools.build:gradle
    versions:
    - 4.1.3
  - dependency-name: org.jetbrains.kotlinx:kotlinx-coroutines-android
    versions:
    - 1.4.3-native-mt
  - dependency-name: org.jetbrains.kotlinx:kotlinx-coroutines-test
    versions:
    - 1.4.3-native-mt
  - dependency-name: org.jetbrains.kotlinx:kotlinx-coroutines-core
    versions:
    - 1.4.3-native-mt
  - dependency-name: com.kirich1409.viewbindingpropertydelegate:vbpd-noreflection
    versions:
    - 1.4.2
  - dependency-name: com.android.tools:desugar_jdk_libs
    versions:
    - 1.1.5
