name: Compose CI

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

jobs:
  compose_ui_test_job:
    name: Compose UI-tests on Android emulator
    runs-on: macos-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        api-level: [ 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31 ]
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Cached Gradle
        uses: actions/cache@v2
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Run Compose UI-tests on Android emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: google_apis
          script: ./gradlew :compose-android:connectedCheck
      - name: Archive ui-tests-output artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: output-compose-ui-tests-artifacts
          path: |
            compose-android/build/outputs
            compose-android/build/reports