name: Desktop Java CI/CD

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

jobs:
  build_job:
    name: Package
    runs-on: [ubuntu-latest, macos-latest, windows-latest]
    continue-on-error: true
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Cached Konan
        uses: actions/cache@v2
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-konan-
      - name: Cached Gradle
        uses: actions/cache@v2
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-
      - name: Set up JDK 15
        uses: actions/setup-java@v1
        with:
          java-version: 15
      - name: Packaging
        run: ./gradlew package
      - name: Archive ui-tests-output artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: output-ui-tests-artifacts
          path: |
            desktop/build/compose/binaries/main/deb
            desktop/build/compose/binaries/main/dmg
            desktop/build/compose/binaries/main/msi