name: iOS CD

on:
  push:
    tags:
      - ios/*

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Cached Konan
        uses: actions/cache@v2
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-konan-
      - name: Cached Gradle
        uses: actions/cache@v2
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-
      - name: Decrypt large secret
        run: ./.github/scripts/decrypt_secret.sh
        env:
          LARGE_SECRET_PASSPHRASE: ${{ secrets.LARGE_SECRET_PASSPHRASE }}
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Download the Apple Worldwide Developer Relations Intermediate Certificate
        working-directory: ./iosApp/fastlane
        run: curl -o AppleWWDRCAG3.cer https://www.apple.com/certificateauthority/AppleWWDRCAG3.cer
      - name: Install the Apple certificate and provisioning profile
        continue-on-error: true # TODO remove
        working-directory: ./iosApp
        env:
          LARGE_SECRET_PASSPHRASE: ${{ secrets.LARGE_SECRET_PASSPHRASE }}
          KEYCHAIN_NAME: app-signing
        run: fastlane setup_certificates_lane
      - name: AppStore build lane with gym
        continue-on-error: true # TODO remove
        working-directory: ./iosApp
        run: fastlane appstore_build_gym_lane
      - name: AppStore test lane with scan
        continue-on-error: true # TODO remove
        working-directory: ./iosApp
        run: fastlane appstore_test_scan_lane
      - name: AppStore publish lane with deliver
        continue-on-error: true # TODO remove
        working-directory: ./iosApp
        run: fastlane appstore_publish_deliver_lane
      - name: Archive build artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: test-artifacts
          path: |
            iosApp/iosApp.app.dSYM.zip
            iosApp/iosApp.ipa
            iosApp/fastlane/test_output/report.html
            /Users/runner/Library/Logs/gym/iosApp-iosApp.log
            /Users/runner/Library/Logs/scan/iosApp-iosApp.log